version: "3"

services:
  api:
    container_name: task-copilot-api
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: develop
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/github.com/km1110/task-copilot-server
  postgresql:
    container_name: task-copilot-postgresql
    build:
      context: ./db/postgresql
      dockerfile: Dockerfile
    tty: true
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - task-copilot-postgresql-vol:/var/lib/postgresql
      - ./db/postgresql/initdb.d:/docker-entrypoint-initdb.d
  redis:
    container_name: task-copilot-redis
    image: redis:latest
    tty: true
    restart: always
    ports:
      - 6379:6379
    volumes:
      - task-copilot-redis-vol:/data

volumes:
  task-copilot-postgresql-vol:
  task-copilot-redis-vol:
